apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  master.conf: |-
  {{- include "configmap.master" . | indent 4 }}
  slave.conf: |-
  {{- include "configmap.slave" . | indent 4 }}
  sentinel.conf: |-
  {{- include "configmap.sentinel" . | indent 4 }}
  