apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: default
  labels:
    web: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: qiujiahong/busybox:latest
        ports:
        - containerPort: 6379