apiVersion: v1
kind: Service
metadata:
  name: redis-m
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis-m
---
apiVersion: v1
kind: Service
metadata:
  name: redis-s
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis-s
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sen
spec:
  ports:
  - port: 26379
    name: redis
  clusterIP: None
  selector:
    app: redis-sen