apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-m
spec:
  selector:
    matchLabels:
      app: redis-m 
  serviceName: "redis-m"
  replicas: 1 
  template:
    metadata:
      labels:
        app: redis-m 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:5.0.6-buster
        # command: ["redis-server"]
        # args: ["/etc/redis/6379.conf"]
        command: ["/bin/sh","-c"]
        args: ["cd /etc/redis/ && cp -rf cm6379.conf 6379.conf && redis-server /etc/redis/6379.conf"]
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/redis/cm6379.conf
          subPath: master.map
      volumes:
        - name: config-volume
          configMap:
            name: redis-conf
            items:
            - key: master.conf # config map中的key
              path: master.map # 给其他地方引用
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-s
spec:
  selector:
    matchLabels:
      app: redis-s
  serviceName: "redis-s"
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-s
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:5.0.6-buster
        # command: ["redis-server"]
        # args: ["/etc/redis/6379.conf"]
        command: ["/bin/sh","-c"]
        args: ["cd /etc/redis/ && cp -rf cm6379.conf 6379.conf && redis-server /etc/redis/6379.conf"]
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/redis/cm6379.conf
          subPath: slave.map
      volumes:
        - name: config-volume
          configMap:
            name: redis-conf
            items:
            - key: slave.conf # config map中的key
              path: slave.map # 给其他地方引用
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sen
spec:
  selector:
    matchLabels:
      app: redis-sen
  serviceName: "redis-sen"
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sen
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:5.0.6-buster
        # command: ["redis-sentinel"]
        # args: ["/etc/redis/26379.conf"]
        command: ["/bin/sh","-c"]
        args: ["cd /etc/redis/ && cp -rf cm26379.conf 26379.conf && redis-sentinel /etc/redis/26379.conf"]
        ports:
        - containerPort: 26379
          name: redis-port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/redis/cm26379.conf
          subPath: sentinel.map
          readOnly: false
      volumes:
        - name: config-volume
          configMap:
            name: redis-conf
            items:
            - key: sentinel.conf # config map中的key
              path: sentinel.map # 给其他地方引用
              
