apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-m
spec:
  selector:
    matchLabels:
      app: redis-m 
  serviceName: "redis-m"
  replicas: 2 
  template:
    metadata:
      labels:
        app: redis-m 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:5.0.6-buster
        ports:
        - containerPort: 6379
          name: redis-port
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: redis-m1
# spec:
#   selector:
#     matchLabels:
#       app: redis-m1 
#   serviceName: "redis-m1"
#   replicas: 1 # by default is 1
#   template:
#     metadata:
#       labels:
#         app: redis-m1 # has to match .spec.selector.matchLabels
#     spec:
#       terminationGracePeriodSeconds: 10
#       containers:
#       - name: redis-m1
#         image: redis:5.0.6-buster
#         ports:
#         - containerPort: 6379
#           name: redis-m1
