apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: redis-m1
# spec:
#   selector:
#     matchLabels:
#       app: redis-m1 
#   serviceName: "redis-m1"
#   replicas: 1 # by default is 1
#   template:
#     metadata:
#       labels:
#         app: redis-m1 # has to match .spec.selector.matchLabels
#     spec:
#       terminationGracePeriodSeconds: 10
#       containers:
#       - name: redis-m1
#         image: redis:5.0.6-buster
#         ports:
#         - containerPort: 6379
#           name: redis-m1
